version: '3.7'

services:
  postgres:
    image: postgres:13.1
    restart: always
    environment:
      POSTGRES_DB: event_service_db
      POSTGRES_USER: event_service_db_user
      POSTGRES_PASSWORD: event_service_db_user_pass
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5404:5432
    volumes:
      - event-pg-data:/var/lib/postgresql/data/

volumes:
  event-pg-data:
